HeThongQuanLyDuLich/Models/HinhAnh.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeThongQuanLyDuLich.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class HinhAnh
    {
        public int IDHinhAnh { get; set; }
        [Display(Name = "Hình ảnh")]
        public byte[] imageUrl { get; set; }
        [Display(Name = "Tour")]
        public Nullable<int> IDTour { get; set; }
        public Nullable<int> IDLoaiHinhAnh { get; set; }

        public virtual LoaiHinhAnh LoaiHinhAnh { get; set; }
        public virtual Tour Tour { get; set; }
    }
}

HeThongQuanLyDuLich/Areas/Admin/Controllers/HinhAnhController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HeThongQuanLyDuLich.Areas.Admin.Code;
using HeThongQuanLyDuLich.Models;
using PagedList;
using PagedList.Mvc;

namespace HeThongQuanLyDuLich.Areas.Admin.Controllers
{
    public class HinhAnhController : Controller
    {
        private HeThongQuanLyDuLichEntities db = new HeThongQuanLyDuLichEntities();
        Random rnd = new Random();

        // GET: Admin/HinhAnh
        [Authorize]
        public ActionResult Index(int? page, string searchValue)
        {
            List<HinhAnh> dsHinhAnh = new List<HinhAnh>();

            if (searchValue == null)
            {
                dsHinhAnh = db.HinhAnhs.Include(h => h.Tour).Include(h => h.LoaiHinhAnh).ToList();
            } else
            {
                string[] temp = searchValue.Split('+');
                string a = string.Join(" ", temp).ToLower();
                dsHinhAnh = db.HinhAnhs.Include(h => h.Tour).Include(h => h.LoaiHinhAnh).Where(s => s.Tour.tourName.ToLower().Contains(a)).ToList();
            }
            int pageSize = 8;
            int pageNum = (page ?? 1);
            return View(dsHinhAnh.ToPagedList(pageNum, pageSize));
        }

        // GET: Admin/HinhAnh/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HinhAnh hinhAnh = db.HinhAnhs.Find(id);
            Console.WriteLine(hinhAnh);
            if (hinhAnh == null)
            {
                return HttpNotFound();
            }
            return View(hinhAnh);
        }

        // GET: Admin/HinhAnh/Create
        [Authorize]
        public ActionResult Create()
        {
            ViewBag.IDTour = db.Tours.ToList();
            ViewBag.IDLoaiHinhAnh = new SelectList(db.LoaiHinhAnhs, "IDLoaiHinhAnh", "loaiHinhAnh1");
            return View();
        }

        // POST: Admin/HinhAnh/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "imageUrl,IDTour,IDLoaiHinhAnh")] HinhAnh hinhAnh)
        {
            hinhAnh.IDHinhAnh = RandomHinhAnhID();
            HttpPostedFileBase file = Request.Files["ImageData"];
            ContentRepository service = new ContentRepository();
            int i = service.UploadImageInDatabase(file, hinhAnh);
            if (i == 1)
            {
                return RedirectToAction("Details", "Tour", new { id = hinhAnh.IDTour});
            }

            ViewBag.IDTour = new SelectList(db.Tours, "IDTour", "tourName", hinhAnh.IDTour);
            ViewBag.IDLoaiHinhAnh = new SelectList(db.LoaiHinhAnhs, "IDLoaiHinhAnh", "loaiHinhAnh1", hinhAnh.IDLoaiHinhAnh);
            return View(hinhAnh);
        }

        // GET: Admin/HinhAnh/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HinhAnh hinhAnh = db.HinhAnhs.Find(id);
            if (hinhAnh == null)
            {
                return HttpNotFound();
            }
            ViewBag.IDTour = new SelectList(db.Tours, "IDTour", "tourName", hinhAnh.IDTour);
            ViewBag.IDLoaiHinhAnh = new SelectList(db.LoaiHinhAnhs, "IDLoaiHinhAnh", "loaiHinhAnh1", hinhAnh.IDLoaiHinhAnh);
            return View(hinhAnh);
        }

        // POST: Admin/HinhAnh/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IDHinhAnh,imageUrl,IDTour,IDLoaiHinhAnh")] HinhAnh hinhAnh)
        {

            HttpPostedFileBase file = Request.Files["ImageData"];
            ContentRepository service = new ContentRepository();
            byte[] img = service.ConvertToBytes(file);
            hinhAnh.imageUrl = img;
            if (ModelState.IsValid)
            {
                db.Entry(hinhAnh).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IDTour = new SelectList(db.Tours, "IDTour", "tourName", hinhAnh.IDTour);
            ViewBag.IDLoaiHinhAnh = new SelectList(db.LoaiHinhAnhs, "IDLoaiHinhAnh", "loaiHinhAnh1", hinhAnh.IDLoaiHinhAnh);
            return View(hinhAnh);
        }

        // GET: Admin/HinhAnh/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HinhAnh hinhAnh = db.HinhAnhs.Find(id);
            if (hinhAnh == null)
            {
                return HttpNotFound();
            }
            return View(hinhAnh);
        }

        // POST: Admin/HinhAnh/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            HinhAnh hinhAnh = db.HinhAnhs.Find(id);
            db.HinhAnhs.Remove(hinhAnh);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        //Display images
        public ActionResult RetrieveImage(int id)
        {
            byte[] cover = GetImageFromDataBase(id);
            if (id != null)
            {
                return File(cover, "image/jpg");
            }
            else
            {
                return null;
            }
        }

        public byte[] GetImageFromDataBase(int id)
        {
            var q = from temp in db.HinhAnhs where temp.IDHinhAnh == id select temp.imageUrl;
            byte[] cover = q.First();
            return cover;
        }

        public int RandomHinhAnhID()
        {
            int num = rnd.Next(1, 10000);
            foreach (var x in db.HinhAnhs)
            {
                if (x.IDHinhAnh == num)
                {
                    RandomHinhAnhID();
                }
            }
            return num;
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HeThongQuanLyDuLich/Areas/Admin/Views/HinhAnh/Create.cshtml
@model HeThongQuanLyDuLich.Models.HinhAnh

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "HinhAnh", FormMethod.Post, new { enctype= "multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>HinhAnh</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        

        <div class="form-group">
            <input type="file" name="ImageData" id="ImageData" class="control-label col-md-2"/>
            <div class="col-md-10">
                @Html.EditorFor(model => model.imageUrl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.imageUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IDTour, "IDTour", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.IDTour, new SelectList(ViewBag.IDTour, "IDTour", "tourName"), htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IDTour, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IDLoaiHinhAnh, "IDLoaiHinhAnh", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IDLoaiHinhAnh", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IDLoaiHinhAnh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

HeThongQuanLyDuLich/Areas/Admin/Views/HinhAnh/Delete.cshtml
@model HeThongQuanLyDuLich.Models.HinhAnh

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Xóa hình ảnh</h2>

<h3>Bạn có chắc chắc muốn xóa ?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.imageUrl)
        </dt>

        <dd>
            <img src="/HinhAnh/RetrieveImage/@Model.IDHinhAnh" height=200 width=300 />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tour.tourName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tour.tourName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LoaiHinhAnh.loaiHinhAnh1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoaiHinhAnh.loaiHinhAnh1)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xóa" class="btn btn-danger" /> |
            @Html.ActionLink("Quay về", "Index")
        </div>
    }
</div>

HeThongQuanLyDuLich/Areas/Admin/Views/HinhAnh/Details.cshtml
@model HeThongQuanLyDuLich.Models.HinhAnh

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Chi tiết hình ảnh</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.imageUrl)
        </dt>

        <dd>
            <img src="/HinhAnh/RetrieveImage/@Model.IDHinhAnh" height=200 width=300 />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tour.tourName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tour.tourName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LoaiHinhAnh.loaiHinhAnh1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoaiHinhAnh.loaiHinhAnh1)
        </dd>

    </dl>
</div>
<button class="btn btn-warning my-button">
    @Html.ActionLink("Chỉnh sửa", "Edit", new { id = Model.IDHinhAnh }, new { @class = "my-class" })
</button>
<button class="btn btn-danger my-button">
    @Html.ActionLink("Xóa", "Delete", new { id = Model.IDHinhAnh }, new { @class = "my-class" })
</button>
<span>
    |
    @Html.ActionLink("Quay về", "Index")
</span>

HeThongQuanLyDuLich/Areas/Admin/Views/HinhAnh/Edit.cshtml
@model HeThongQuanLyDuLich.Models.HinhAnh

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Chỉnh sửa hình ảnh</h2>

@using (Html.BeginForm("Edit", "HinhAnh", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IDHinhAnh)

        <div class="form-group">
            <input type="file" name="ImageData" id="ImageData" class="control-label col-md-2" />
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IDTour, "IDTour", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IDTour", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IDTour, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IDLoaiHinhAnh, "IDLoaiHinhAnh", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IDLoaiHinhAnh", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IDLoaiHinhAnh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-success" />
                <button class="btn btn-danger my-button">
                    @Html.ActionLink("Hủy", "Index", null, new { @class = "my-class" })
                </button>
            </div>
        </div>
    </div>
}

HeThongQuanLyDuLich/Areas/Admin/Views/HinhAnh/Index.cshtml
@using PagedList.Mvc;
@model PagedList.PagedList<HeThongQuanLyDuLich.Models.HinhAnh>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Danh sách hình ảnh</h2>

<button class="btn btn-danger my-button">
    @Html.ActionLink("Thêm mới", "Create", null, new { @class = "my-class" })
</button>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().imageUrl)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Tour.tourName)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>

            <td>
                <img src="/HinhAnh/RetrieveImage/@item.IDHinhAnh" height=100 width=200 />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tour.tourName)
            </td>
            <td>
                <button class="btn btn-info my-button">
                    @Html.ActionLink("Chi tiết ", "Details", new { id = item.IDHinhAnh }, new { @class = "my-class" })
                </button>
            </td>
        </tr>
    }

</table>

<div style="margin-left: 1rem">
    Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount

    <div>
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))
    </div>
</div>